### ISSUE TITLE
Why Flutter-aware?

### ISSUE THREAD

**Issue by igorkamyshev** [purplenoodlesoop/flutter_effector#6]
Hello! I am curious, why this implementation dedicated to Flutter?

Original effector is completely independent from any UI-frameworks.

Why do you decide to write Flutter-aware implementation of Dart? Why not effector_dart?

**Comment by purplenoodlesoop** [comment]
Hi! 

You are completely right — it should not be that way! 

In one of the next merges there will be a spit into a dart_effector and flutter_effector packages. 

Thank you for your feedback!

**Comment by mit-73** [comment]
Hi @igorkamyshev , I will answer on my own behalf for now, maybe the author will support me or correct me.

Yes, we also plan to make a completely UI framework-independent library. The current developments are planned to be divided into two packages (most likely their names will be effector or dart_effector and flutter_effector) and the repository itself should also change its name, as it seems to me.

In fact, everything happened spontaneously, we decided to test the concept, that's why there are such small mistakes.

**Comment by igorkamyshev** [comment]
Thanks for answers.
